### PR TITLE
redo the way we handle prod deps

### PR DESCRIPTION
**Pull request by zkat**
Fixes: https://github.com/NuGet/setup-nuget/issues/15

In the time since I originally wrote this task and now, the template over at https://github.com/actions/typescript-action has been updated with a much better way of doing prod stuff. The reason for #15 is actually that some packages in node_modules were _partially_ committed, but this no longer relies on that directory being in git. I believe this will fix all outstanding issues, once we get it to the v1 branch.

### CODE REVIEW

**Comment by dylan-smith** [comment]
I think part of the recent problem too was node_modules was in gitignore, so my PR that updated @actions/core only picked up the changed files in node_modules and not the net new files.

**Comment by zkat** [comment]
@dylan-smith yup, that's basically what happened, I think.

**Comment by dylan-smith** [comment]
I was gonna take a look at the tests you have when I have a bit of free time, see if I can make any improvements that would catch stuff like this

**Comment by zkat** [comment]
@dylan-smith that would be awesome! Thank you!

**Review by nkolev92 — APPROVED** [review]

**Pull request merged**
