### PR TITLE
Updated actions/core package to 1.2.6

### PR DESCRIPTION
**Pull request by dylan-smith**
There was a recent change GitHub actions that results in warnings if your using an older version of the core toolkit - https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Currently the setup-nuget action is throwing 2 warnings because of this as mentioned in #11   

Updating to the latest @actions/core package should fix this without any further changes required.

NOTE: I have NOT tested these changes yet.

### CODE REVIEW

**Comment by dnfgituser** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/NuGet/setup-nuget?pullRequest=12) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/NuGet/setup-nuget?pullRequest=12) before we can accept your contribution.<br/><br/>:x: dylan-smith [sign now](https://cla.dotnetfoundation.org/NuGet/setup-nuget?pullRequest=12)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/NuGet/setup-nuget?pullRequest=12) it.</sub>

**Comment by dylan-smith** [comment]
Replaces #10

**Review by nkolev92 — APPROVED** [review]

**Review by priebek — APPROVED** [review]

**Comment by feinoujc** [comment]
@priebek @nkolev92 does this need to be synced with the v1 branch so people can pull this change in automatically? Or at least add a new tag so we don't have to target master? 

https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/

**Comment by priebek** [comment]
> @priebek @nkolev92 does this need to be synced with the v1 branch so people can pull this change in automatically? Or at least add a new tag with the built version?
> 
> https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/
> 
> Related to #11

@nkolev92 Yes, a v1.0.3 would be appreciated.

**Comment by Alex-Yates** [comment]
Can I +1 what others have said? Can we get a v1.0.3 so that I can update my actions to avoid the warnings and prepare for MS removing the set-env feature?

**Comment by nkolev92** [comment]
@zkat Just published v1.0.3

**Comment by Alex-Yates** [comment]
> @zkat just published v1.0.3

THANK YOU!

**Comment by Alex-Yates** [comment]
Ah, yes. As kstolte says. Cannot find module '.\utils':

Run NuGet/setup-nuget@v1.0.3
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module './utils'
Require stack:
- D:\a\_actions\NuGet\setup-nuget\v1.0.3\node_modules\@actions\core\lib\command.js
- D:\a\_actions\NuGet\setup-nuget\v1.0.3\node_modules\@actions\core\lib\core.js
- D:\a\_actions\NuGet\setup-nuget\v1.0.3\lib\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\a\_actions\NuGet\setup-nuget\v1.0.3\node_modules\@actions\core\lib\command.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\a\\_actions\\NuGet\\setup-nuget\\v1.0.3\\node_modules\\@actions\\core\\lib\\command.js',
    'D:\\a\\_actions\\NuGet\\setup-nuget\\v1.0.3\\node_modules\\@actions\\core\\lib\\core.js',
    'D:\\a\\_actions\\NuGet\\setup-nuget\\v1.0.3\\lib\\main.js'
  ]
}

**Comment by nkolev92** [comment]
Hey @ale

**Comment by Alex-Yates** [comment]
> Hey @Alex-Yates, we had to publish a new version, 1.0.5.
> 
> There were some issues with 1.0.3 and 1.0.4 that @zkat has resolved.

Thanks so much! Really appreciate it. 👍

**Pull request merged**
